spring.application.name=simple

spring.datasource.driverClassName=org.h2.Driver
spring.datasoure.username=sa
spring.datasource.password=
spring.datasource.url=jdbc:h2:mem:testdb



#logging.pattern.console =${CONSOLE_LOG_PATTERN:%d{yyyy-MM-dd HH:mm:ss}  \%blue(%-5level) %red ([%thread0) %yellow(%logger{15})- %msg%n}
